
TOOL_NAME=SSHTunnels

TOOL_OBJECTS=main.o log.o util.o tunnel.o

CFLAGS+=-Wall -O0 -g `pkg-config --cflags expat`
LDFLAGS+=-Wall -lm `pkg-config --libs expat`

all: $(TOOL_NAME)
	@echo All Done

$(TOOL_NAME): $(TOOL_OBJECTS)
	$(CC) $(LDFLAGS) -o $(TOOL_NAME) $(TOOL_OBJECTS)

clean:
	rm -f SSHTunnels *.o


