
TOOL_NAME=SSHTunnels

TOOL_OBJECTS=main.o log.o util.o tunnel.o

CFLAGS+=-Wall -O2
LDFLAGS+=-Wall -lm

all: $(TOOL_NAME)
	@echo All Done

$(TOOL_NAME): $(TOOL_OBJECTS)
	$(CC) $(LDFLAGS) -o $(TOOL_NAME) $(TOOL_OBJECTS)

clean:
	rm -f SSHTunnels *.o


